export const ORDER_STATUS = {
  WAITING_FOR_PAYMENT: "WAITING_FOR_PAYMENT",
  PAID: "PAID",
  DELIVERED: "DELIVERED",
  COMPLETED: "COMPLETED"
}

export const ORDER_SHIPPING = {
  ORDER_ORIGIN: 501,
  ORDER_COURIER: "jne"
}
